apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mydep
    tier: apptire
spec:
  replicas: 4
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
        - name: redis
          image: redis
  selector:
