version: '3'

services:
  # Database
  db:
    image: mysql:8.0.23
    volumes:
     - /var/lib/mysql_data:/var/lib/mysql
     - ./config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passowrd
      MYSQL_DATABASE: DATABASEDB
      MYSQL_USER: testusr
      MYSQL_PASSWORD: passowrd
    expose:
      - 3306
    ports:
      - 3306:3306
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - '8899:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passowrd
  # Keycloak
  keycloak:
    depends_on:
      - db
    image: jboss/keycloak:12.0.2
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_DATABASE: KEYCLOAK
      DB_USER: keycloak
      DB_PASSWORD: passowrd
      DB_PORT: 3306
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: passowrd
    ports:
      - 8181:8080
    expose:
      - 8181
    links:
      - db
volumes:
  v_keycloak_data:
